version: '3.8'

networks:
  sistemodev:

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - sistemodev

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - '5432:5432'
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    networks:
      - sistemodev

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
